### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Funryr** [khasang-incubator/Android-20160131#137]
Баги, обнаруженные при написании описания
1. Клик по ВК альбому, попадаем в альбом и видим общее количество фотографий.
Клик по фотографии и потом возврат общего  количества фотографий уже нет.
2. В общих настройках надо указать язык не Russian, а Русский.
3. В уведомлениях два пункта не переведены на русский
4. Аналогично и в настройках синхронизации, там же стоит цифра 60: надо указать ед. измерения (мин, час, год).
5. Частота синхронизации надо написать значения к пунктам

**Comment by xzaleksey** [comment]
1 починил

**Comment by Funryr** [comment]
В настройках синхронизации убрал текст Vibration with notification, а галочку оставил.

**Comment by Funryr** [comment]
Убрал

**Comment by xzaleksey** [comment]
Done.
