### ISSUE TITLE
Find All Photo Albums on Device

### ISSUE THREAD

**Issue by bugtsa** [khasang-incubator/Android-20160131#5]
Поиск всех папок с фотографиями на устройстве

**Comment by taalay** [comment]
Создан класс LocalPhoto для локальных фотографии

Создан класс LocalAlbums содержащий в себе Map с ключом название альбома и листом объектов LocalPhoto

класс LocalAlbums
    публичные методы
    public List<String> getPhotosPath(String albumName)
    public List<LocalPhoto> getPhotos(String albumName)
    public List<String> getAlbums()
    public void showInLogAllPhotos()
