### ISSUE TITLE
Delete Albums from device

### ISSUE THREAD

**Issue by devtau** [khasang-incubator/Android-20160131#59]
Реализовать функцию удаления альбомов из локальных альбомов.
Разделить функционал на физическое удаление и обновление вью по модели MVP.
Спрашивать подтверждение пользователя на удаление альбома / альбомов.

**Comment by Tau025** [comment]
попутный фикс загрузки больших фото с помощью пикассо

**Comment by Tau025** [comment]
попутный фикс неточного метода LocalAlbumSource.getAllLocalAlbums()

**Comment by Tau025** [comment]
перенести содержимое метода LocalAlbumsCursorLoader. loadInBackground() в LocalAlbumSource.getAllLocalAlbums(). вызывать второй из первого

**Comment by Tau025** [comment]
убрать неиспользуемые методы getAllLocalAlbums() из интерфейов LocalAlbumsInteractor и LocalAlbumsPresenter

**Comment by Tau025** [comment]
вынести функционал поиска альбома по содержащейся в нем фотографии из LocalPhotoSource.deleteLocalPhotos в новый метод LocalAlbumSource.getAlbumByPhoto

**Comment by Tau025** [comment]
баг: обложки альбомов отображаются узкими полосами на большом экране. заменить ImageView album_thumb из photoalbum_item.xml на набор подставляемых xml файлов через include

**Comment by Tau025** [comment]
дополнить конструктор Photo(String filePath) поиском локального id подгружаемой фотографии и сохранять его, как Photo.id Конфликта с id фотографий вк быть не должно из-за больших значений последнего

**Comment by Tau025** [comment]
делать замер экрана устройства и устанавливать пропорции обложки альбома 16:9

**Comment by devtau** [comment]
реализовано физическим удалением файлов с устройства. это не правильно, тк вызывает баги отображения удаленных фото в галерее. contentresolver также продолжает видеть удаленные фото некоторое время
