### ISSUE TITLE
Finish local albums delete

### ISSUE THREAD

**Issue by xzaleksey** [khasang-incubator/Android-20160131#84]

**Comment by devtau** [comment]
опасно удалять папку с фотками с камеры. саму камеру потом на эмуляторе запустить получается не всегда)

**Comment by devtau** [comment]
неоднозначно поведение программы при удалении локальных синхронизированных с контактом фото. сейчас мы не удаляем их из бд, хотя должны по логике формирования альбома вк (см ишью 83). больше того, по логике надо еще и у юзера спросить, а не подразумевает ли он удаление их и из вк, и после подтверждения запускать синхронизацию чтобы удалить их из вк

**Comment by devtau** [comment]
попутно фикс размера прогрессбара синхронизируемого альбома до 50*50 дп

**Comment by devtau** [comment]
попутно фикс неправильного количества фотографий в синхронизированном альбоме

**Comment by devtau** [comment]
merged
