### ISSUE TITLE
Fix Albums directory

### ISSUE THREAD

**Issue by xzaleksey** [khasang-incubator/Android-20160131#85]

**Comment by devtau** [comment]
private void galleryAddPic() {
    Intent mediaScanIntent = new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE);
    File f = new File(mCurrentPhotoPath);
    Uri contentUri = Uri.fromFile(f);
    mediaScanIntent.setData(contentUri);
    this.sendBroadcast(mediaScanIntent);
}
http://stackoverflow.com/questions/8560501/android-save-image-into-gallery

**Comment by devtau** [comment]
попутный фикс получения NPE в LocalAlbumSource.getAllLocalAlbums на пустом альбоме

**Comment by devtau** [comment]
merged
